version: '3.8'

services:
  db:
    image: postgres:13
    container_name: backend-ad-campaign-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: backend_db
    ports:
      - "5432:5432"
    volumes:
      - backend-ad-campaign_pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: backend-ad-campaign-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    depends_on:
      - db

  app:
    build:
      context: .
    container_name: backend-ad-campaign-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: example
      DB_NAME: backend_db

volumes:
  backend-ad-campaign_pgdata:
